# Generated by Django 5.2.5 on 2025-10-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=300)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('ano', models.IntegerField()),
                ('volume', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('arquivo_pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos_editores/')),
            ],
        ),
        migrations.CreateModel(
            name='SlideCarrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='slides/')),
                ('link_leia_mais', models.URLField()),
            ],
        ),
    ]
