# Generated by Django 5.2.5 on 2025-10-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidecarrossel',
            name='link_leia_mais',
        ),
        migrations.AddField(
            model_name='slidecarrossel',
            name='conteudo_detalhado',
            field=models.TextField(blank=True, help_text="Conteúdo completo que aparecerá na página 'Leia Mais'."),
        ),
        migrations.AddField(
            model_name='slidecarrossel',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para URL (será preenchido automaticamente se deixado em branco)', max_length=110, unique=True),
        ),
    ]
