# Generated by Django 5.2.5 on 2025-10-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0002_remove_slidecarrossel_link_leia_mais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidecarrossel',
            name='slug',
            field=models.SlugField(blank=True, max_length=110, unique=True),
        ),
    ]
