# Generated by Django 5.2.5 on 2025-08-25 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0002_editor_slidecarrossel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='resumo',
            new_name='conteudo',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='volume',
        ),
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.CharField(default='Equipe BPG', max_length=100),
        ),
        migrations.AddField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(default='', upload_to='artigos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artigo',
            name='legenda_imagem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(default='slug-temporario', help_text="Texto único para a URL, ex: 'sobre-o-bpg'", unique=True),
            preserve_default=False,
        ),
    ]
