# Generated by Django 5.2.5 on 2025-10-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0003_alter_slidecarrossel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos_parceiros/')),
                ('link_externo', models.URLField(blank=True, help_text='Opcional: Link para o site do parceiro.')),
            ],
        ),
    ]
